apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: terraform-aws-cloudfront
  namespace: tx-pts-dai
  description: terraform-aws-cloudfront component
  annotations:
    github.com/project-slug: tx-pts-dai/terraform-aws-cloudfront
  tags:
    - tx-pts-dai
spec:
  type: infrastructure
  lifecycle: production
  owner: group:default/dai